import { Metadata } from "next";

const MetaData: Metadata = {
  title: "Home | curlylogic",
  description:
    "'Welcome to curlylogic: Your Source for Cutting-Edge Technology Insights'. curlylogic is your go-to destination for staying at the forefront of the ever-evolving world of technology. Our platform serves as a dynamic hub where tech enthusiasts, professionals, and curious minds converge to explore the latest trends, insights, and breakthroughs across a multitude of technologies.",
  keywords: [
    "Next.js",
    "React",
    "JavaScript",
    "Python",
    "Pandas",
    "Numpy",
    "Html",
    "Html5",
    "Css",
    "Css3",
    "EcmaScript",
    "es6",
    "es7",
    "es8",
    "es9",
    "ES2015",
    "ES2016",
    "ES2017",
    "ES2018",
    "ES2019",
    "ES2020",
    "ES2021",
    "ES2022",
    "ES2023",
    "ESNEXT",
    "TypeScript",
    "Node.js",
    "Mongo",
    "Angular",
    "Git",
    "Github",
    "Front-end",
    "Development",
    "UI development",
    "UI design",
    "US design",
    "UI/UX",
    "sanity",
    "Headless CMS",
    "Contentful",
    "Vercel",
    "Analysis",
    "Data analysis",
    "Data",
    "Excel",
    "Data science",
    "Exploratory Data Analysis",
    "EDA",
    "Netlify",
    "Time Series Analysis",
    "Time-Series Analysis",
    "RFM Analysis",
    "Data Wrangling",
    "Data Manipulation",
    "Data Cleaning",
    "Front-end Architecture",
    "Data Mining",
    "Data Profiling",
    "Sci-kit Learn",
    "Scikit Learn",
    "sklearn",
    "statsmodel",
    "plotly",
    "anaconda",
    "jupyter notebook",
    "jupyter lab",
    "matplotlib",
    "plotly express",
    "seaborn",
    "Tensorflow",
  ],
};

export default MetaData;
